version = 1

test_patterns = ["tests/**/test_*.py"]

exclude_patterns = [
    "assets/**",
    "docs/**",
    "docsrc/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
