name: Upload Vectorhub Nightly

on:
  schedule:
    - cron: "0 0 * * *"
# on:
#   push:
#     branches:
#       - feature/add_vectorhub_nightly

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PW }}
        IS_VECTORHUB_NIGHTLY: True
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
