name: Run Pytest 3.6

on:
  push:
    branches:
      - main
    paths:
      - 'vectorhub/**'
      - 'tests/**'
      - 'setup.py'
  pull_request:
    branches:
      - main
    # paths:
    #   - 'vectorhub/**'
    #   - 'tests/**'
    #   - 'setup.py'

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pytest 3.6
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install base dependencies
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          sudo apt-get install libsndfile1
          python -m pip install --upgrade pip
          pip install -e .

      - name: Install dependencies for tests
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pip install -r requirements.txt
          pip install -e ".[test]"
      - name: Test Vectorai models
        env:
            VI_USERNAME: ${{ secrets.VI_USERNAME }}
            VI_API_KEY: ${{ secrets.VI_API_KEY }}
        run: |
          pytest tests/encoders/image/vectorai

      - name: Install and test for image-tfhub
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pip install -e ".[encoders-image-tfhub]"
          pytest tests/encoders/image/tfhub

      - name: Install and test for image-fastai
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pip install -e ".[encoders-image-fastai]"
          pytest tests/encoders/image/fastai
      
      - name: Install and test for face2vec models
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pip install -e .["encoders-image-tensorflow-face-detection"]
          pytest tests/encoders/image/tensorflow

      - name: Test cases for Autoencoder
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pytest -v -m image
